CREATE TABLE IF NOT EXISTS `BI_OLAP`.`DM_Customer` (
  `CustomerID` INT NOT NULL,
  `Name` VARCHAR(255) NOT NULL,
  `BirthDate` DATE NOT NULL,
  `Age` INT NOT NULL,
  `Gender` VARCHAR(15) NOT NULL,
  `Email` VARCHAR(255) NOT NULL,
  `Phone` INT NULL,
  CONSTRAINT PK_CustomerID PRIMARY KEY (`CustomerID`))
